name: Update Publications Page

# Trigger on pushes to PDFs folder or manual trigger
on:
  push:
    paths:
      - 'pdfs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Generate index.html dynamically
      - name: Build index.html from PDFs
        run: |
          echo "<!DOCTYPE html>
          <html lang='en'>
          <head>
          <meta charset='UTF-8'>
          <meta name='viewport' content='width=device-width, initial-scale=1.0'>
          <title>McWilliams Lab Publications</title>
          <style>
            body{font-family:sans-serif;margin:2rem;color:#333;}
            h1{font-size:2rem;color:#2b4b80;}
            .pub-item{margin-bottom:1.2rem;}
            a{color:#0066cc;text-decoration:none;}
            a:hover{text-decoration:underline;}
          </style>
          </head>
          <body>
          <h1>McWilliams Lab Publications</h1>
          <p>Below are downloadable PDFs from our lab:</p>
          <div class='pub-list'>" > index.html

          # Loop over PDFs and append HTML entries
          for f in pdfs/*.pdf; do
            fname=$(basename "$f")
            year=$(echo "$fname" | grep -oE '[0-9]{4}' || echo "Unknown Year")
            title=$(echo "$fname" | sed -E 's/[-_]/ /g' | sed 's/.pdf//')
            echo "<div class='pub-item'><a href='$f' target='_blank'>$year — $title</a> <a href='$f' download>(Download PDF)</a></div>" >> index.html
          done

          echo "</div><footer><p>© 2025 McWilliams Lab</p></footer></body></html>" >> index.html

      # 3️⃣ Commit and push updated index.html
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Auto-update publications list" || echo "No changes to commit"
          git push
