name: Update Publications Page

on:
  push:
    paths:
      - 'pdfs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate publications list
        run: |
          echo "<!DOCTYPE html>
          <html><head><meta charset='UTF-8'><title>McWilliams Lab Publications</title>
          <style>
            body{font-family:sans-serif;margin:2rem;color:#333;}
            h1{color:#2b4b80;}
            .pub-item{margin-bottom:1rem;}
            a{color:#0066cc;text-decoration:none;}
            a:hover{text-decoration:underline;}
          </style>
          </head><body>
          <h1>McWilliams Lab Publications</h1>
          <p>Below are PDFs available from our lab.</p>" > index.html

          for f in pdfs/*.pdf; do
            fname=$(basename "$f")
            year=$(echo "$fname" | grep -oE '[0-9]{4}' || echo "")
            echo "<div class='pub-item'><a href='$f' target='_blank'>$year — $fname</a></div>" >> index.html
          done

          echo "<footer><p>© 2025 McWilliams Lab</p></footer></body></html>" >> index.html

      - name: Commit updated index.html
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Auto-update publications list" || echo "No changes to commit"
          git push
