name: Update Publications Page

permissions:
  contents: write

on:
  push:
    paths:
      - 'pdfs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Generate index.html dynamically
      - name: Build index.html from PDFs
        run: |
          echo "<!DOCTYPE html>
          <html lang='en'>
          <head>
          <meta charset='UTF-8'>
          <meta name='viewport' content='width=device-width, initial-scale=1.0'>
          <title>McWilliams Lab Publications</title>
          <style>
            body{font-family:sans-serif;margin:2rem;color:#333;line-height:1.6;}
            h1{font-size:2rem;margin-bottom:1rem;color:#2b4b80;}
            .pub-item{margin-bottom:1.2rem;}
            a{color:#0066cc;text-decoration:none;}
            a:hover{text-decoration:underline;}
            .download{margin-left:0.5rem;font-size:0.9rem;}
            footer{margin-top:3rem;font-size:0.8rem;color:#777;border-top:1px solid #eee;padding-top:1rem;}
          </style>
          </head>
          <body>
          <h1>McWilliams Lab Publications</h1>
          <p>Below are research papers and PDFs made publicly available by the McWilliams Lab. Click the title to view or download.</p>
          <div class='pub-list'>" > index.html

          # Loop over PDFs and append HTML entries
          for f in pdfs/*.pdf; do
            fname=$(basename "$f")
            # Extract year if present in filename
            year=$(echo "$fname" | grep -oE '[0-9]{4}' || echo "Unknown Year")
            # Create title from filename
            title=$(echo "$fname" | sed -E 's/[-_]/ /g' | sed 's/.pdf//')
            echo "<div class='pub-item'>
                    <a href='pdfs/$fname' target='_blank'>$year — $title</a>
                    <a class='download' href='pdfs/$fname' download>(Download PDF)</a>
                  </div>" >> index.html
          done

          echo "</div><footer>© 2025 McWilliams Lab — Licensed under CC BY-SA 4.0</footer></body></html>" >> index.html

      # 3️⃣ Commit and push updated index.html
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Auto-update publications list" || echo "No changes to commit"
          git push
