name: Update Publications Page

permissions:
  contents: write

on:
  push:
    paths:
      - 'pdfs/**'
      - 'metadata.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install yq for YAML parsing
        run: sudo apt-get update && sudo apt-get install -y yq

      - name: Build index.html from metadata.yml
        run: |
          echo "<!DOCTYPE html>
          <html lang='en'>
          <head>
            <meta charset='UTF-8'>
            <meta name='viewport' content='width=device-width, initial-scale=1.0'>
            <title>McWilliams Lab Publications</title>
            <style>
              body { font-family: sans-serif; margin: 2rem; color: #333; line-height: 1.6; }
              h1 { font-size: 2rem; margin-bottom: 1rem; color: #2b4b80; }
              .pub-item { margin-bottom: 1.2rem; }
              a { color: #0066cc; text-decoration: none; }
              a:hover { text-decoration: underline; }
              .download { margin-left: 0.5rem; font-size: 0.9rem; }
              footer { margin-top: 3rem; font-size: 0.8rem; color: #777; border-top: 1px solid #eee; padding-top: 1rem; }
            </style>
          </head>
          <body>
            <h1>McWilliams Lab Publications</h1>
            <p>Below are research papers and PDFs made publicly available by the McWilliams Lab. Click the title to view or download.</p>
            <div class='pub-list'>" > index.html

          # Loop through metadata.yml
          for i in $(seq 0 $(($(yq '. | length' metadata.yml)-1))); do
            file=$(yq ".[$i].file" metadata.yml)
            title=$(yq ".[$i].title" metadata.yml)
            author=$(yq ".[$i].author" metadata.yml)
            year=$(yq ".[$i].year" metadata.yml)

            echo "<div class='pub-item'>
              <a href=\"pdfs/$file\" target='_blank'>$year — $title</a>
              <span> $author</span>
              <a class='download' href=\"pdfs/$file\" download>(Download PDF)</a>
            </div>" >> index.html
          done

          echo "</div><footer>© 2025 McWilliams Lab — Licensed under CC BY-SA 4.0</footer></body></html>" >> index.html

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Auto-update publications list from metadata.yml" || echo "No changes to commit"
          git push
