name: Update Publications Page

permissions:
  contents: write

on:
  push:
    paths:
      - 'pdfs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Generate index.html dynamically
      - name: Build index.html from PDFs
        run: |
          # Start the HTML file
          cat << 'EOF' > index.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>McWilliams Lab Publications</title>
<style>
body{font-family:sans-serif;margin:2rem;color:#333;line-height:1.6;}
h1{font-size:2rem;margin-bottom:1rem;color:#2b4b80;}
.pub-item{margin-bottom:1.2rem;}
a{color:#0066cc;text-decoration:none;}
a:hover{text-decoration:underline;}
.download{margin-left:0.5rem;font-size:0.9rem;}
footer{margin-top:3rem;font-size:0.8rem;color:#777;border-top:1px solid #eee;padding-top:1rem;}
</style>
</head>
<body>
<h1>McWilliams Lab Publications</h1>
<p>Below are research papers and PDFs made publicly available by the McWilliams Lab. Click the title to view or download.</p>
<div class='pub-list'>
EOF

          # Loop over PDFs safely (handles spaces and special characters)
          shopt -s nullglob
          for f in pdfs/*.pdf; do
            fname=$(basename "$f")
            
            # Extract the first 4-digit year in the filename, fallback to Unknown Year
            year=$(echo "$fname" | grep -oE '[0-9]{4}' | head -n1 || echo "Unknown Year")
            
            # Remove the year and .pdf extension to get a clean title
            title=$(echo "$fname" | sed -E "s/$year//" | sed -E 's/\.pdf$//' | sed -E 's/[-_]/ /g' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            
            # Escape special HTML characters in title
            title_escaped=$(echo "$title" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g')
            
            # Append entry to index.html
            echo "<div class='pub-item'>
  <a href='pdfs/$fname' target='_blank'>$year — $title_escaped</a>
  <a class='download' href='pdfs/$fname' download>(Download PDF)</a>
</div>" >> index.html
          done

          # Close HTML file
          echo "</div><footer>© 2025 McWilliams Lab — Licensed under CC BY-SA 4.0</footer></body></html>" >> index.html

      # 3️⃣ Commit and push updated index.html
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Auto-update publications list" || echo "No changes to commit"
          git push
